---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-7.10
  - name: debian-8.4
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[virtualbox]
