
driver:
  name: vagrant

verifier:
  name: inspec

transport:
  username: vagrant
  password: vagrant
  elevated: true
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-16.10
  - name: debian-8.6
  - name: centos-6.8
  - name: centos-7.2
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
      gui: false

suites:
- name: default
  run_list:
    - recipe[virtualbox]
  attributes:
